# Hyprlock Configuration (GNOME Adwaita Style)

$font = Ubuntu

general {
    hide_cursor = false
    grace = 0
}

auth {
    fingerprint {
        enabled = true
        ready_message = Or scan fingerprint
        present_message = Scanning fingerprint...
        retry_delay = 250
    }
}

animations {
# Animations have the potential to not complete before a suspend operation is
# run, showing the unblurred screen briefly before locking on wake.
    enabled = false
}

background {
    monitor =
    color = rgb(25, 25, 25)
}

# PASSWORD INPUT FIELD
input-field {
    monitor =
    size = 700, 100 
    outline_thickness = 3
    dots_size = 0.32
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgba(255, 255, 255, 0.25)
    inner_color = rgba(30, 30, 30, 0.85)
    font_color = rgb(255, 255, 255)
    font_family = $font

    fade_on_empty = false
    rounding = 22

    placeholder_text = <span foreground="##ffffff99" font="Ubuntu 28"><i>Enter Password...</i></span>
    check_color = rgba(53, 132, 228, 1.0) # GNOME Blue
    fail_color = rgba(246, 97, 81, 1.0)   # GNOME Red
    fail_text = <span font="Ubuntu 24"><i>Authentication failed ($ATTEMPTS)</i></span>

    position = 0, -60
    halign = center
    valign = center
}

# FINGERPRINT / STATUS PROMPT
label {
    monitor =
    text = $FPRINTPROMPT
    font_size = 28
    font_family = $font
    color = rgba(255, 255, 255, 0.85)

    position = 0, -175
    halign = center
    valign = center
}
